var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                              o                           x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                           xxxxxx                         x  ",
   "  x                       o                   x                              x  ",
   "  x                                 xxxxx     x                xxxxxxxxxx    x  ",
   "  x                                     x!!!!!x         xx     x             x  ",
   "  x                                     x!!!!!x                x             x  ",
   "  x        $           xxxxxxxx         xxxxxxx                x      xxxxxxxx  ",
   "  x                                     xxxxxxx              # x             x  ",
   "  x  @                               o  xxxxxxx  o             x          o  x  ",
   "  xxxxxxxxxxxxxxxxxx              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                   x              x                                             ",
   "                   x!!!!!!!!!!!!!!x                                             ",
   "                   x!!!!!!!!!!!!!!x                                             ",
   "                   xxxxxxxxxxxxxxxx                                             ",
   "                                                                                ",
   "                                                                                "],


  ["  x                                                            xxxxxxxvxxxxxxx  ",
   "  x                                                            x             x  ",
   "  x                                                            x           o x  ",
   "  x                                                            x             x  ",
   "  x                        xxxx           xxxx                 x        xxxxxx  ",
   "  x                                                            x o           x  ",
   "  x                   o                            o           x             x  ",
   "  x @                                                          xxxxxx        x  ",
   "  xxxxxxxx          xxxx           xxxx          xxxx          x           o x  ",
   "  x                                                            x             x  ",
   "  x                                                            x        xxxxxx  ",
   "  x                                                            x o           x  ",
   "  x          xxxx          xxxx           xxxx                 x             x  ",
   "  x                                                            xxxxxx        x  ",
   "  x      o                           o                         x           o x  ",
   "  x                                                                          x  ",
   "  x    xxxx         xxxx           xxxx                                      x  ",
   "  x                                                     xxxxxxxxxxxxxxxxxxxxxx  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                       ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                       ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       "],
 

  ["                                                                                    ",
   "  x                                                                              x  ",
   "  x                                          o                                   x  ",
   "  x                                                                              x  ",
   "  x                                                                              x  ",
   "  x           o                                                                o x  ",
   "  x                                o       xxxxx                  o              x  ",
   "  x         xxxx                           xxxxx                                 x  ",
   "  x         xxxx                           xxxxx                                 x  ",
   "  x @       xxxx                xxxxx      xxxxx         o       xxxx       xxxxxx  ",
   "  xxxx      xxxx        o       xxxxx      xxxxx                 xxxx       xxxxxx  ",
   "  xxxx      xxxx                xxxxx      xxxxx                 xxxx       xxxxxx  ",
   "  xxxx      xxxx      xxxx      xxxxx      xxxxx       xxxx      xxxx       xxxxxx  ",
   "  xxxx      xxxx      xxxx      xxxxx      xxxxx       xxxx      xxxx       xxxxxx  ",
   "  xxxx      xxxx      xxxx      xxxxx      xxxxx       xxxx      xxxx       xxxxxx  ",
   "  xxxx      xxxx      xxxx      xxxxx      xxxxx       xxxx      xxxx       xxxxxx  ",
   "  xxxx      xxxx      xxxx      xxxxx      xxxxx       xxxx      xxxx       xxxxxx  ",
   "  xxxx!!!!!!xxxx!!!!!!xxxx!!!!!!xxxxx!!!!!!xxxxx!!!!!!!xxxx!!!!!!xxxx!!!!!!!xxxxxx  ",
   "  xxxx!!!!!!xxxx!!!!!!xxxx!!!!!!xxxxx!!!!!!xxxxx!!!!!!!xxxx!!!!!!xxxx!!!!!!!xxxxxx  ",
   "  xxxx!!!!!!xxxx!!!!!!xxxx!!!!!!xxxxx!!!!!!xxxxx!!!!!!!xxxx!!!!!!xxxx!!!!!!!xxxxxx  ",
   "  xxxx!!!!!!xxxx!!!!!!xxxx!!!!!!xxxxx!!!!!!xxxxx!!!!!!!xxxx!!!!!!xxxx!!!!!!!xxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                    ",
   "                                                                                   "],


[  "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                #                                         x  ",
   "  x  @          x    x                               x    x                  x  ",
   "  xxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxx      x  ",
   "  xxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxx      x  ",
   "  x                                                                       o  x  ",
   "  x                                                                          x  ",
   "  x                                                                       o  x  ",
   "  x                                                                          x  ",
   "  x                           #                       #                   o  x  ",
   "  x      x                             x                              x      x  ",
   "  x      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x   o                                                                      x  ",
   "  x                                                                          x  ",
   "  x   o                                                                 o    x  ",
   "  x                                                                    o o   x  ",
   "  x   o                                                               o o o  x  ",
   "  x                                                                  o o o o x  ",
   "  xxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxx!!!!xxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],

[  "  x        x   x   xxxx   x    x            x  ",
   "  x         x x    x  x   x    x            x  ",
   "  x          x     x  x   x    x            x  ",
   "  x          x     xxxx    xxxx             x  ",
   "  x                                         x  ",
   "  x     x       x   xxx   xx    x    x      x  ",
   "  x     x       x    x    x xx  x    x      x  ",
   "  x     x  xxx  x    x    x  xx x           x  ",
   "  x     xxx   xxx   xxx   x    xx    x      x  ",
   "  x                                         x  ",
   "  x                   @                     x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  "]
 ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
